FROM python:alpine3.21

ARG LPORT=1911
ARG WORKDIR=/server

# Create a non-root user and group
RUN addgroup --system appgroup && adduser --system --ingroup appgroup appuser

WORKDIR ${WORKDIR}

ENV VIRTUAL_ENV=${WORKDIR}/venv
ENV PATH="${VIRTUAL_ENV}/bin:$PATH"

COPY . .

RUN python -m venv $VIRTUAL_ENV && \
  pip install --upgrade pip && \
  pip install --no-cache-dir -r requirement.txt

# Change ownership of the working directory to writeable by appuser
RUN chown -R appuser:appgroup ${WORKDIR}

EXPOSE ${LPORT}

# Switch to the non-root user
USER appuser

CMD ["python", "server.py"]
