FROM python:3.13-slim

ARG LPORT=1911
ARG WORKDIR=/server

WORKDIR ${WORKDIR}

ENV VIRTUAL_ENV=${WORKDIR}/venv
ENV PATH="${VIRTUAL_ENV}/bin:$PATH"

COPY . .

RUN python -m venv $VIRTUAL_ENV && \
  pip install --upgrade pip && \
  pip install --no-cache-dir -r requirement.txt

EXPOSE ${LPORT}

CMD ["python", "server.py"]

