FROM python:3-slim-bookworm AS builder

ARG WORKDIR=/server
ENV WORKDIR=${WORKDIR}
WORKDIR ${WORKDIR}

RUN apt-get update -y && \
  apt-get install -y --no-install-recommends \
  build-essential \
  libffi-dev \
  python3-dev \
  curl \
  ca-certificates \
  && rm -rf /var/lib/apt/lists/*

RUN curl -L "https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz" -o ffmpeg.tar.xz && \
  tar -xvf ffmpeg.tar.xz && \
  # Çıkarılan klasörün adı değişebilir, bu yüzden joker karakter (*) kullanıyoruz
  mv ffmpeg-git-*-static/ffmpeg /usr/local/bin/ffmpeg && \
  # Arşiv ve çıkarılan klasörleri temizle
  rm -rf ffmpeg.tar.xz ffmpeg-git-*-static

ENV VIRTUAL_ENV=${WORKDIR}/venv
ENV PATH="${VIRTUAL_ENV}/bin:$PATH"

COPY requirement.txt .
RUN python -m venv $VIRTUAL_ENV && \
  pip install --no-cache-dir -r requirement.txt

COPY . .


FROM gcr.io/distroless/python3-debian12:nonroot

ARG LPORT=1911
ARG WORKDIR=/server
ENV WORKDIR=${WORKDIR}
WORKDIR ${WORKDIR}

COPY --from=builder --chown=65532:65532 ${WORKDIR}/venv ${WORKDIR}/venv
COPY --from=builder --chown=65532:65532 ${WORKDIR} ${WORKDIR}

COPY --from=builder --chown=65532:65532 /usr/local/bin/ffmpeg /usr/local/bin/ffmpeg

ENV VIRTUAL_ENV=${WORKDIR}/venv
ENV PATH="${VIRTUAL_ENV}/bin:/usr/local/bin:$PATH"

EXPOSE ${LPORT}

USER nonroot

# CMD ["/server/venv/bin/python", "/server/server.py"]
